using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Autodesk.AutoCAD.DatabaseServices;
using HydroComplete.Civil3D.Reading;
using HydroComplete.Engine;

namespace HydroComplete.Civil3D.Writing
{
    /// <summary>
    /// Formula-transparent HTML report for Manning pipe capacity checks.
    /// </summary>
    internal static class HtmlReportWriter
    {
        public static string Write(
            string drawingName,
            IReadOnlyList<ReadPipe> pipes,
            IReadOnlyDictionary<ObjectId, Manning.CapacityResult> capacities)
        {
            string folder = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "HydroComplete");
            Directory.CreateDirectory(folder);

            string stamp = DateTime.Now.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture);
            string safeDrawing = SanitizeFileName(drawingName);
            string path = Path.Combine(folder, $"report-{safeDrawing}-{stamp}.html");

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\"/>");
            sb.AppendLine("<title>HydroComplete Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#1a1a1a;}");
            sb.AppendLine("h1{font-size:1.4rem;} table{border-collapse:collapse;width:100%;margin:16px 0;}");
            sb.AppendLine("th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;font-size:0.9rem;}");
            sb.AppendLine("th{background:#f0f4f8;} .steps{font-family:Consolas,monospace;font-size:0.85rem;}");
            sb.AppendLine(".disclaimer{margin-top:24px;padding:12px;background:#fff8e6;border:1px solid #e6c200;}");
            sb.AppendLine("</style></head><body>");
            sb.AppendLine("<h1>HydroComplete — Manning Pipe Capacity Report</h1>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Drawing: <strong>{0}</strong><br/>Generated: {1}</p>",
                Escape(drawingName), Escape(DateTime.Now.ToString("f", CultureInfo.CurrentCulture))));
            sb.AppendLine("<p>Method: Manning full-barrel capacity for circular pipes (US customary, n=0.013 default).</p>");

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Network / Pipe</th><th>Dia (ft)</th><th>Slope</th><th>Q<sub>full</sub> (cfs)</th><th>V<sub>full</sub> (fps)</th>");
            sb.AppendLine("</tr></thead><tbody>");

            foreach (ReadPipe rp in pipes)
            {
                if (!capacities.TryGetValue(rp.PipeId, out Manning.CapacityResult? cap))
                    continue;

                sb.AppendLine("<tr>");
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<td>{0}</td><td>{1:0.00}</td><td>{2:0.0000}</td><td>{3:0.00}</td><td>{4:0.00}</td>",
                    Escape(Trim(rp.NetworkName + "/" + rp.PipeName, 48)),
                    rp.Segment.DiameterFt, rp.Segment.Slope,
                    cap.FullFlowCfs, cap.FullVelocityFps));
                sb.AppendLine("</tr>");
            }

            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<h2>Calculation steps</h2>");
            foreach (ReadPipe rp in pipes)
            {
                if (!capacities.TryGetValue(rp.PipeId, out Manning.CapacityResult? cap))
                    continue;

                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<h3>{0}</h3><div class=\"steps\">",
                    Escape(Trim(rp.NetworkName + "/" + rp.PipeName, 64))));
                foreach (CalcStep step in cap.Steps)
                    sb.AppendLine(Escape(step.ToString()) + "<br/>");
                sb.AppendLine("</div>");
            }

            sb.AppendLine("<div class=\"disclaimer\">");
            sb.AppendLine("<strong>Disclaimer:</strong> This report is generated by HydroComplete for preliminary ");
            sb.AppendLine("storm-sewer review. Verify all inputs (diameter, slope, roughness) against the ");
            sb.AppendLine("engineer's design basis. Not a substitute for licensed professional judgment or ");
            sb.AppendLine("jurisdiction-specific design standards.");
            sb.AppendLine("</div>");
            sb.AppendLine("</body></html>");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            return path;
        }

        private static string SanitizeFileName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "drawing";
            foreach (char c in Path.GetInvalidFileNameChars())
                name = name.Replace(c, '_');
            return name.Trim();
        }

        private static string Escape(string s)
        {
            return s
                .Replace("&", "&amp;", StringComparison.Ordinal)
                .Replace("<", "&lt;", StringComparison.Ordinal)
                .Replace(">", "&gt;", StringComparison.Ordinal)
                .Replace("\"", "&quot;", StringComparison.Ordinal);
        }

        private static string Trim(string s, int max)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Length <= max ? s : s.Substring(0, max - 1) + "~";
        }
    }
}