using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Autodesk.AutoCAD.DatabaseServices;
using HydroComplete.Civil3D.Reading;
using HydroComplete.Engine;

namespace HydroComplete.Civil3D.Writing
{
    /// <summary>
    /// Formula-transparent HTML report for Manning pipe capacity and steady HGL profiles.
    /// </summary>
    internal static class HtmlReportWriter
    {
        public static string Write(
            string drawingName,
            IReadOnlyList<ReadPipe> pipes,
            IReadOnlyDictionary<ObjectId, Manning.CapacityResult> capacities,
            HglReportData? hglData = null,
            CapacityReportData? capacityData = null,
            StormwaterReportData? stormwaterData = null)
        {
            string path = ReportWriterCommon.BuildReportPath(drawingName, "html");

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\"/>");
            sb.AppendLine("<title>HydroComplete Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#1a1a1a;}");
            sb.AppendLine("h1{font-size:1.4rem;} h2{font-size:1.15rem;margin-top:28px;}");
            sb.AppendLine("table{border-collapse:collapse;width:100%;margin:16px 0;}");
            sb.AppendLine("th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;font-size:0.9rem;}");
            sb.AppendLine("th{background:#f0f4f8;} tr.surcharged{background:#ffe6e6;}");
            sb.AppendLine(".steps{font-family:Consolas,monospace;font-size:0.85rem;}");
            sb.AppendLine(".disclaimer{margin-top:24px;padding:12px;background:#fff8e6;border:1px solid #e6c200;}");
            sb.AppendLine("</style></head><body>");
            sb.AppendLine("<h1>HydroComplete — Hydraulic Report</h1>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Drawing: <strong>{0}</strong><br/>Generated: {1}</p>",
                ReportWriterCommon.EscapeHtml(drawingName),
                ReportWriterCommon.EscapeHtml(DateTime.Now.ToString("f", CultureInfo.CurrentCulture))));

            AppendManningSection(sb, pipes, capacities);

            if (capacityData != null && capacityData.Rows.Count > 0)
                AppendCapacitySection(sb, capacityData);

            if (hglData != null && hglData.Networks.Count > 0)
                AppendHglSection(sb, hglData);

            if (stormwaterData != null && stormwaterData.HasContent)
                AppendStormwaterSections(sb, stormwaterData);

            sb.AppendLine("<div class=\"disclaimer\">");
            sb.AppendLine("<strong>Disclaimer:</strong> This report is generated by HydroComplete for preliminary ");
            sb.AppendLine("storm-sewer review. Verify all inputs (diameter, slope, roughness, design flow) ");
            sb.AppendLine("against the engineer's design basis. Not a substitute for licensed professional ");
            sb.AppendLine("judgment or jurisdiction-specific design standards.");
            sb.AppendLine("</div>");
            sb.AppendLine("</body></html>");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            return path;
        }

        /// <summary>Standalone stormwater HTML report (detention, BMP sizing, treatment train, sediment basin).</summary>
        public static string WriteStormwater(string drawingName, StormwaterReportData data)
        {
            string path = ReportWriterCommon.BuildReportPath(drawingName, "stormwater.html");

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\"/>");
            sb.AppendLine("<title>HydroComplete Stormwater Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#1a1a1a;}");
            sb.AppendLine("h1{font-size:1.4rem;} h2{font-size:1.15rem;margin-top:28px;}");
            sb.AppendLine("table{border-collapse:collapse;width:100%;margin:16px 0;}");
            sb.AppendLine("th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;font-size:0.9rem;}");
            sb.AppendLine("th{background:#f0f4f8;}");
            sb.AppendLine(".steps{font-family:Consolas,monospace;font-size:0.85rem;}");
            sb.AppendLine(".disclaimer{margin-top:24px;padding:12px;background:#fff8e6;border:1px solid #e6c200;}");
            sb.AppendLine("</style></head><body>");
            sb.AppendLine("<h1>HydroComplete — Stormwater Report</h1>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Drawing: <strong>{0}</strong><br/>Generated: {1}</p>",
                ReportWriterCommon.EscapeHtml(drawingName),
                ReportWriterCommon.EscapeHtml(DateTime.Now.ToString("f", CultureInfo.CurrentCulture))));

            AppendStormwaterSections(sb, data);

            sb.AppendLine("<div class=\"disclaimer\">");
            sb.AppendLine("<strong>Disclaimer:</strong> Detention routing, BMP sizing, and sediment basin ");
            sb.AppendLine("calculations are preliminary. Verify stage-storage curves, outlet hydraulics, ");
            sb.AppendLine("and jurisdictional BMP criteria against licensed professional judgment.");
            sb.AppendLine("</div>");
            sb.AppendLine("</body></html>");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            return path;
        }

        private static void AppendStormwaterSections(StringBuilder sb, StormwaterReportData data)
        {
            if (data.Detention != null)
                AppendDetentionSection(sb, data.Detention);
            if (data.BmpSizing != null)
                AppendBmpSizingSection(sb, data.BmpSizing);
            if (data.TreatmentTrain != null)
                AppendTreatmentTrainSection(sb, data.TreatmentTrain);
            if (data.SedimentBasin != null)
                AppendSedimentBasinSection(sb, data.SedimentBasin);
        }

        private static void AppendDetentionSection(StringBuilder sb, DetentionReportSection section)
        {
            DetentionRouting.RoutingResult routing = section.Result;
            sb.AppendLine("<h2>Detention Pond Routing</h2>");
            sb.AppendLine("<p>Method: Modified Puls (storage indication). Inflow from SCS unit hydrograph ");
            sb.AppendLine("scaled by composite SCS CN runoff depth.</p>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Storage: <strong>{0}</strong><br/>Drainage area = {1:0.000} ac, Tc = {2:0.0} min, " +
                "runoff depth = {3:0.###} in.</p>",
                ReportWriterCommon.EscapeHtml(section.StorageDescription),
                section.DrainageAreaAcres, section.SystemTcMinutes, section.RunoffDepthIn));

            if (section.OutletDescriptions.Count > 0)
            {
                sb.AppendLine("<p>Outlets: ");
                sb.AppendLine(string.Join(", ",
                    section.OutletDescriptions.Select(ReportWriterCommon.EscapeHtml)));
                sb.AppendLine("</p>");
            }

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Q<sub>in,peak</sub> (cfs)</th><th>Q<sub>out,peak</sub> (cfs)</th>");
            sb.AppendLine("<th>Attenuation (%)</th><th>S<sub>max</sub> (ft³)</th><th>Peak elev (ft)</th>");
            sb.AppendLine("</tr></thead><tbody><tr>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<td>{0:0.00}</td><td>{1:0.00}</td><td>{2:0.1}</td><td>{3:0}</td><td>{4:0.##}</td>",
                routing.PeakInflowCfs, routing.PeakOutflowCfs, routing.ReductionPercent,
                routing.PeakStorageFt3, routing.PeakElevationFt));
            sb.AppendLine("</tr></tbody></table>");

            if (routing.Ordinates.Count > 0)
            {
                sb.AppendLine("<h3>Routing hydrograph</h3>");
                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>t (hr)</th><th>Q<sub>in</sub> (cfs)</th><th>Q<sub>out</sub> (cfs)</th>");
                sb.AppendLine("<th>S (ft³)</th><th>Elev (ft)</th>");
                sb.AppendLine("</tr></thead><tbody>");
                foreach (DetentionRouting.RoutingOrdinate ord in routing.Ordinates)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<tr><td>{0:0.##}</td><td>{1:0.00}</td><td>{2:0.00}</td><td>{3:0}</td><td>{4:0.##}</td></tr>",
                        ord.TimeHours, ord.InflowCfs, ord.OutflowCfs, ord.StorageFt3, ord.ElevationFt));
                }
                sb.AppendLine("</tbody></table>");
            }

            sb.AppendLine("<h3>Routing calculation steps</h3><div class=\"steps\">");
            foreach (CalcStep step in routing.Steps)
                sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
            sb.AppendLine("</div>");
        }

        private static void AppendBmpSizingSection(StringBuilder sb, BmpSizingReportSection section)
        {
            WaterQualityEngine.BmpSizingResult sizing = section.Result;
            sb.AppendLine("<h2>BMP Sizing (WQV)</h2>");
            sb.AppendLine("<p>Method: WQV = Rv &times; P &times; A &times; 3630 cf/ac-in; BMP surface area/length ");
            sb.AppendLine("from treated volume per BMP type.</p>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>BMP: <strong>{0}</strong> ({1})<br/>Area = {2:0.000} ac, I = {3:0.#}%, " +
                "design storm = {4:0.##} in.</p>",
                ReportWriterCommon.EscapeHtml(sizing.BmpName),
                ReportWriterCommon.EscapeHtml(sizing.BmpType),
                section.DrainageAreaAcres, section.ImperviousPercent, section.DesignStormInches));

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>WQV (cf)</th><th>V<sub>treated</sub> (cf)</th><th>Surface area (sf)</th>");
            sb.AppendLine("<th>Footprint (%)</th><th>Length (ft)</th><th>Width (ft)</th>");
            sb.AppendLine("</tr></thead><tbody><tr>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<td>{0:0}</td><td>{1:0}</td><td>{2:0}</td><td>{3:0.##}</td><td>{4}</td><td>{5}</td>",
                sizing.TotalWqvCf, sizing.TreatedVolumeCf, sizing.SurfaceAreaSf, sizing.FootprintPercent,
                sizing.LengthFt.HasValue ? sizing.LengthFt.Value.ToString("0.0", CultureInfo.InvariantCulture) : "—",
                sizing.WidthFt.HasValue ? sizing.WidthFt.Value.ToString("0.0", CultureInfo.InvariantCulture) : "—"));
            sb.AppendLine("</tr></tbody></table>");

            sb.AppendLine("<h3>BMP sizing calculation steps</h3><div class=\"steps\">");
            foreach (CalcStep step in sizing.Steps)
                sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
            sb.AppendLine("</div>");
        }

        private static void AppendTreatmentTrainSection(StringBuilder sb, TreatmentTrainReportSection section)
        {
            WaterQualityEngine.TreatmentTrainResult train = section.Result;
            sb.AppendLine("<h2>BMP Treatment Train</h2>");
            sb.AppendLine("<p>Method: EMC event loads from catchments; sequential BMP mass balance ");
            sb.AppendLine("(η<sub>total</sub> = 1 &minus; &prod;(1 &minus; η<sub>i</sub>)).</p>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Land use = <strong>{0}</strong>, runoff depth = {1:0.###} in, area = {2:0.000} ac.<br/>",
                ReportWriterCommon.EscapeHtml(section.LandUse), section.RunoffDepthIn, section.DrainageAreaAcres));
            sb.AppendLine("Chain: " + string.Join(" &rarr; ",
                section.BmpChain.Select(k => ReportWriterCommon.EscapeHtml(BmpLibrary.GetBmp(k).Name))) + "</p>");

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Pollutant</th><th>Influent (lbs)</th><th>Effluent (lbs)</th>");
            sb.AppendLine("<th>Removed (lbs)</th><th>Overall η (%)</th>");
            sb.AppendLine("</tr></thead><tbody>");
            foreach (string pollutant in Pollutant.Core)
            {
                train.InitialLoadsLbs.TryGetValue(pollutant, out double influent);
                train.FinalEffluentLbs.TryGetValue(pollutant, out double effluent);
                train.TotalRemovedLbs.TryGetValue(pollutant, out double removed);
                train.OverallRemovalEfficiency.TryGetValue(pollutant, out double eta);
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<tr><td>{0}</td><td>{1:0.####}</td><td>{2:0.####}</td><td>{3:0.####}</td><td>{4:0.1}</td></tr>",
                    pollutant, influent, effluent, removed, eta * 100.0));
            }
            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<h3>Treatment train calculation steps</h3><div class=\"steps\">");
            foreach (CalcStep step in train.Steps)
                sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
            sb.AppendLine("</div>");
        }

        private static void AppendSedimentBasinSection(StringBuilder sb, SedimentBasinReportSection section)
        {
            SedimentBasin.DesignResult design = section.Result;
            sb.AppendLine("<h2>Sediment Basin Design</h2>");
            sb.AppendLine("<p>Method: NCDEQ surface-area ratio (A<sub>s</sub> = Q &times; 435 sf/cfs), ");
            sb.AppendLine("pool volume, sediment storage, and forebay.</p>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Design Q = <strong>{0:0.00} cfs</strong>, drainage area = {1:0.000} ac, " +
                "sediment yield = {2:0.##} tons/ac/yr.</p>",
                section.DesignFlowCfs, section.DrainageAreaAcres, section.SedimentYieldTonsPerAcreYr));

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Surface area (sf)</th><th>L (ft)</th><th>W (ft)</th><th>Depth (ft)</th>");
            sb.AppendLine("<th>Pool vol (cf)</th><th>Sed storage (cf)</th><th>Total vol (cf)</th>");
            sb.AppendLine("<th>Trapping (%)</th>");
            sb.AppendLine("</tr></thead><tbody><tr>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<td>{0:0}</td><td>{1:0.0}</td><td>{2:0.0}</td><td>{3:0.0}</td>" +
                "<td>{4:0}</td><td>{5:0}</td><td>{6:0}</td><td>{7:0.#}</td>",
                design.SurfaceAreaSf, design.LengthFt, design.WidthFt, design.DepthFt,
                design.PoolVolumeCf, design.SedimentStorageCf, design.TotalVolumeCf,
                design.TrappingEfficiencyPct));
            sb.AppendLine("</tr></tbody></table>");

            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Forebay: {0:0} cf ({1:0.0} &times; {2:0.0} ft), dewatering = {3:0} hr ({4}).</p>",
                design.ForebayVolumeCf, design.ForebayLengthFt, design.ForebayWidthFt,
                design.DewateringTimeHr, ReportWriterCommon.EscapeHtml(design.TrapEfficiencyMethod)));

            sb.AppendLine("<h3>Sediment basin calculation steps</h3><div class=\"steps\">");
            foreach (CalcStep step in design.Steps)
                sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
            sb.AppendLine("</div>");
        }

        private static void AppendManningSection(
            StringBuilder sb,
            IReadOnlyList<ReadPipe> pipes,
            IReadOnlyDictionary<ObjectId, Manning.CapacityResult> capacities)
        {
            sb.AppendLine("<h2>Manning Pipe Capacity</h2>");
            sb.AppendLine("<p>Method: Manning full-barrel capacity for circular pipes (US customary, n=0.013 default).</p>");

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Network / Pipe</th><th>Dia (ft)</th><th>Slope</th><th>Q<sub>full</sub> (cfs)</th><th>V<sub>full</sub> (fps)</th>");
            sb.AppendLine("</tr></thead><tbody>");

            foreach (ReadPipe rp in pipes)
            {
                if (!capacities.TryGetValue(rp.PipeId, out Manning.CapacityResult? cap))
                    continue;

                sb.AppendLine("<tr>");
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<td>{0}</td><td>{1:0.00}</td><td>{2:0.0000}</td><td>{3:0.00}</td><td>{4:0.00}</td>",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(rp.NetworkName + "/" + rp.PipeName, 48)),
                    rp.Segment.DiameterFt, rp.Segment.Slope,
                    cap.FullFlowCfs, cap.FullVelocityFps));
                sb.AppendLine("</tr>");
            }

            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<h3>Manning calculation steps</h3>");
            foreach (ReadPipe rp in pipes)
            {
                if (!capacities.TryGetValue(rp.PipeId, out Manning.CapacityResult? cap))
                    continue;

                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<h4>{0}</h4><div class=\"steps\">",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(rp.NetworkName + "/" + rp.PipeName, 64))));
                foreach (CalcStep step in cap.Steps)
                    sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
                sb.AppendLine("</div>");
            }
        }

        private static void AppendCapacitySection(StringBuilder sb, CapacityReportData capacityData)
        {
            sb.AppendLine("<h2>Design Capacity Check</h2>");
            string qDesc = capacityData.IsRouted
                ? string.Format(CultureInfo.InvariantCulture,
                    "per-pipe routed catchment Q (system total = <strong>{0:0.00} cfs</strong>)",
                    capacityData.DesignFlowCfs)
                : string.Format(CultureInfo.InvariantCulture,
                    "uniform design Q = <strong>{0:0.00} cfs</strong>",
                    capacityData.DesignFlowCfs);
            sb.AppendLine("<p>Method: Manning normal depth at " + qDesc + ". " +
                "Surcharge when Q exceeds peak open-channel capacity (d/D &rarr; 1.0).</p>");

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Network / Pipe</th><th>Q<sub>full</sub> (cfs)</th><th>Q<sub>des</sub> (cfs)</th>");
            sb.AppendLine("<th>Q<sub>des</sub>/Q<sub>full</sub></th><th>d/D</th><th>SURCH</th>");
            sb.AppendLine("</tr></thead><tbody>");

            foreach (CapacityPipeRow row in capacityData.Rows)
            {
                ReadPipe rp = row.Pipe;
                string rowClass = row.Surcharged ? " class=\"surcharged\"" : "";
                sb.AppendLine($"<tr{rowClass}>");
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<td>{0}</td><td>{1:0.0}</td><td>{2:0.0}</td><td>{3:0.00}</td><td>{4:0.00}</td><td>{5}</td>",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(rp.NetworkName + "/" + rp.PipeName, 48)),
                    row.QFullCfs, row.DesignFlowCfs, row.FlowRatio, row.RelativeDepth,
                    row.Surcharged ? "*" : ""));
                sb.AppendLine("</tr>");
            }

            sb.AppendLine("</tbody></table>");
        }

        private static void AppendHglSection(StringBuilder sb, HglReportData hglData)
        {
            string lossNote = hglData.IncludeMinorLosses ? " with HEC-22 junction/exit losses" : "";
            sb.AppendLine("<h2>Steady HGL Profile</h2>");
            string hglQDesc = hglData.IsRouted
                ? string.Format(CultureInfo.InvariantCulture,
                    "per-pipe routed catchment Q (system total = <strong>{0:0.00} cfs</strong>)",
                    hglData.DesignFlowCfs)
                : string.Format(CultureInfo.InvariantCulture,
                    "design Q = <strong>{0:0.00} cfs</strong>",
                    hglData.DesignFlowCfs);
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Method: steady uniform-flow stepping downstream from headwater HGL " +
                "using Manning normal depth per reach (partial-flow A and R){0}. " +
                "(S<sub>f</sub> = [n&middot;Q/(1.486&middot;A&middot;R<sup>2/3</sup>)]<sup>2</sup>, " +
                "h<sub>f</sub> = S<sub>f</sub>&middot;L, h<sub>m</sub> = K&middot;Vh). " +
                "{1}.</p>",
                lossNote, hglQDesc));

            foreach (HglNetworkReport net in hglData.Networks)
            {
                if (net.Rows.Count == 0) continue;

                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<h3>{0}</h3><p>Outfall tailwater HGL = {1:0.00} ft (profile stepped upstream from the outfall, adding friction + HEC-22 minor losses).</p>",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(net.NetworkName, 64)), net.StartHglFt));

                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>Pipe</th><th>d/D</th><th>h<sub>f</sub> (ft)</th><th>h<sub>m</sub> (ft)</th>");
                sb.AppendLine("<th>HGL<sub>US</sub> (ft)</th><th>HGL<sub>DS</sub> (ft)</th><th>SURCH</th>");
                sb.AppendLine("</tr></thead><tbody>");

                foreach (HglPipeReportRow row in net.Rows)
                {
                    string rowClass = row.IsSurcharged ? " class=\"surcharged\"" : "";
                    sb.AppendLine($"<tr{rowClass}>");
                    string dOverD = row.FlowSurcharged
                        ? "SURCH"
                        : row.RelativeDepth.ToString("0.00", CultureInfo.InvariantCulture);

                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<td>{0}</td><td>{1}</td><td>{2:0.00}</td><td>{3:0.00}</td><td>{4:0.00}</td><td>{5:0.00}</td><td>{6}</td>",
                        ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(row.PipeName, 48)),
                        dOverD,
                        row.Point.HfFt, row.Point.HmFt,
                        row.HglUsFt, row.HglDsFt,
                        row.IsSurcharged ? "*" : ""));
                    sb.AppendLine("</tr>");
                }

                sb.AppendLine("</tbody></table>");

                sb.AppendLine("<h4>HGL calculation steps</h4>");
                foreach (HglPipeReportRow row in net.Rows)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<h5>{0}</h5><div class=\"steps\">",
                        ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(row.PipeName, 64))));
                    foreach (CalcStep step in row.Point.Steps)
                        sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
                    sb.AppendLine("</div>");
                }
            }
        }

        /// <summary>Full-network analysis HTML report (HC_ANALYZE).</summary>
        public static string WriteAnalysis(
            string drawingName,
            NetworkAnalysisResult result,
            string? idfLabel = null)
        {
            string path = ReportWriterCommon.BuildReportPath(drawingName, "analysis.html");

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\"/>");
            sb.AppendLine("<title>HydroComplete Analysis Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#1a1a1a;}");
            sb.AppendLine("h1{font-size:1.4rem;} h2{font-size:1.15rem;margin-top:28px;}");
            sb.AppendLine("table{border-collapse:collapse;width:100%;margin:16px 0;}");
            sb.AppendLine("th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;font-size:0.9rem;}");
            sb.AppendLine("th{background:#f0f4f8;} tr.fail{background:#ffe6e6;}");
            sb.AppendLine(".steps{font-family:Consolas,monospace;font-size:0.85rem;}");
            sb.AppendLine(".pass{color:#0a6b0a;font-weight:bold;}.failtxt{color:#b00020;font-weight:bold;}");
            sb.AppendLine(".disclaimer{margin-top:24px;padding:12px;background:#fff8e6;border:1px solid #e6c200;}");
            sb.AppendLine("</style></head><body>");
            sb.AppendLine("<h1>HydroComplete — Full Network Analysis</h1>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Drawing: <strong>{0}</strong><br/>Generated: {1}<br/>State: <strong>{2}</strong>",
                ReportWriterCommon.EscapeHtml(drawingName),
                ReportWriterCommon.EscapeHtml(DateTime.Now.ToString("f", CultureInfo.CurrentCulture)),
                ReportWriterCommon.EscapeHtml(result.StateCode)));
            if (!string.IsNullOrWhiteSpace(idfLabel))
                sb.AppendLine("<br/>IDF: " + ReportWriterCommon.EscapeHtml(idfLabel));
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<br/>Overall: <span class=\"{0}\">{1}</span></p>",
                result.OverallPass ? "pass" : "failtxt",
                result.OverallPass ? "PASS" : "FAIL"));

            sb.AppendLine("<h2>Hydrology</h2>");
            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Catchment</th><th>Area (ac)</th><th>C</th><th>Tc (min)</th>");
            sb.AppendLine("<th>Q Rational (cfs)</th><th>SCS runoff (in)</th>");
            sb.AppendLine("</tr></thead><tbody>");
            foreach (CatchmentHydrologyResult hydro in result.Hydrology)
            {
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<tr><td>{0}</td><td>{1:0.000}</td><td>{2:0.00}</td><td>{3:0.0}</td><td>{4:0.00}</td><td>{5:0.###}</td></tr>",
                    ReportWriterCommon.EscapeHtml(hydro.Catchment.Name),
                    hydro.Catchment.AreaAcres, hydro.Catchment.RunoffC, hydro.Catchment.TcMinutes,
                    hydro.Rational.PeakFlowCfs, hydro.Scs.RunoffDepthInches));
            }
            sb.AppendLine("</tbody></table>");

            if (result.Capacity.Count > 0)
            {
                sb.AppendLine("<h2>Pipe Capacity</h2>");
                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>Network / Pipe</th><th>Q (cfs)</th><th>Q/Qfull</th><th>d/D</th><th>Surcharged</th>");
                sb.AppendLine("</tr></thead><tbody>");
                foreach (PipeCapacityAnalysisResult row in result.Capacity)
                {
                    string label = string.IsNullOrEmpty(row.Pipe.NetworkName)
                        ? row.Pipe.PipeName
                        : row.Pipe.NetworkName + "/" + row.Pipe.PipeName;
                    string rowClass = row.Surcharged ? " class=\"fail\"" : "";
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<tr{0}><td>{1}</td><td>{2:0.0}</td><td>{3:0.00}</td><td>{4:0.00}</td><td>{5}</td></tr>",
                        rowClass,
                        ReportWriterCommon.EscapeHtml(label),
                        row.DesignFlowCfs, row.FlowRatio, row.NormalDepth.RelativeDepth,
                        row.Surcharged ? "Yes" : "No"));
                }
                sb.AppendLine("</tbody></table>");
            }

            if (result.HglNetworks.Count > 0)
            {
                sb.AppendLine("<h2>HGL Profiles</h2>");
                foreach (NetworkHglResult net in result.HglNetworks)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<h3>{0}</h3><p>Tailwater = {1:0.00} ft</p>",
                        ReportWriterCommon.EscapeHtml(net.NetworkName), net.TailwaterFt));
                    sb.AppendLine("<table><thead><tr>");
                    sb.AppendLine("<th>Pipe</th><th>Q (cfs)</th><th>HGL US (ft)</th><th>HGL DS (ft)</th><th>h<sub>f</sub> (ft)</th>");
                    sb.AppendLine("</tr></thead><tbody>");
                    for (int i = 0; i < net.OrderedPipes.Count && i < net.Profile.Count; i++)
                    {
                        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                            "<tr><td>{0}</td><td>{1:0.0}</td><td>{2:0.00}</td><td>{3:0.00}</td><td>{4:0.00}</td></tr>",
                            ReportWriterCommon.EscapeHtml(net.OrderedPipes[i].PipeName),
                            net.Reaches[i].FlowCfs,
                            net.Profile[i].HglUpstreamFt,
                            net.Profile[i].HglFt,
                            net.Profile[i].HfFt));
                    }
                    sb.AppendLine("</tbody></table>");
                }
            }

            if (result.Sediment.Count > 0)
            {
                sb.AppendLine("<h2>RUSLE Sediment</h2>");
                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>Catchment</th><th>Soil loss (tons/ac/yr)</th><th>Risk</th>");
                sb.AppendLine("</tr></thead><tbody>");
                foreach (SedimentEngine.RusleResult rusle in result.Sediment)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<tr><td>{0}</td><td>{1:0.##}</td><td>{2}</td></tr>",
                        ReportWriterCommon.EscapeHtml(rusle.Name),
                        rusle.SoilLossTonsPerAcYr, rusle.RiskLevel));
                }
                sb.AppendLine("</tbody></table>");
            }

            if (result.Wqv != null)
            {
                sb.AppendLine("<h2>Water Quality Volume</h2>");
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<p>WQV = {0:0} cf ({1:0.##} ac-ft), Rv = {2:0.###}</p>",
                    result.Wqv.WqvCf, result.Wqv.WqvAcreFt, result.Wqv.RunoffCoefficientRv));
            }

            if (result.TreatmentTrain != null)
            {
                sb.AppendLine("<h2>Placeholder BMP Treatment Train</h2>");
                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>Pollutant</th><th>Influent (lbs)</th><th>Effluent (lbs)</th><th>η (%)</th>");
                sb.AppendLine("</tr></thead><tbody>");
                foreach (string pollutant in Pollutant.Core)
                {
                    result.TreatmentTrain.InitialLoadsLbs.TryGetValue(pollutant, out double influent);
                    result.TreatmentTrain.FinalEffluentLbs.TryGetValue(pollutant, out double effluent);
                    result.TreatmentTrain.OverallRemovalEfficiency.TryGetValue(pollutant, out double eta);
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<tr><td>{0}</td><td>{1:0.##}</td><td>{2:0.##}</td><td>{3:0.#}</td></tr>",
                        pollutant, influent, effluent, eta * 100.0));
                }
                sb.AppendLine("</tbody></table>");
            }

            if (result.Compliance != null)
            {
                sb.AppendLine("<h2>Regulatory Compliance</h2>");
                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>Criterion</th><th>Required</th><th>Actual</th><th>Status</th>");
                sb.AppendLine("</tr></thead><tbody>");
                foreach (ComplianceCriterion c in result.Compliance.Criteria)
                {
                    string rowClass = c.Status == ComplianceStatus.Fail ? " class=\"fail\"" : "";
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<tr{0}><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td></tr>",
                        rowClass,
                        ReportWriterCommon.EscapeHtml(c.Name),
                        ReportWriterCommon.EscapeHtml(c.Required),
                        ReportWriterCommon.EscapeHtml(c.Actual),
                        c.Status));
                }
                sb.AppendLine("</tbody></table>");
            }

            if (result.DesignReview.Count > 0)
            {
                sb.AppendLine("<h2>Design Review Findings</h2><ul>");
                foreach (DesignFinding finding in result.DesignReview)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<li><strong>{0}</strong> {1}: {2}</li>",
                        finding.Severity,
                        ReportWriterCommon.EscapeHtml(finding.Id),
                        ReportWriterCommon.EscapeHtml(finding.Message)));
                }
                sb.AppendLine("</ul>");
            }

            sb.AppendLine("<h2>Pipeline Trace</h2><div class=\"steps\">");
            foreach (CalcStep step in result.Steps)
                sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
            sb.AppendLine("</div>");

            sb.AppendLine("<div class=\"disclaimer\">");
            sb.AppendLine("<strong>Disclaimer:</strong> Full-network analysis is preliminary. ");
            sb.AppendLine("Placeholder BMP treatment assumes bioretention; verify all inputs and ");
            sb.AppendLine("jurisdiction-specific requirements with licensed professional judgment.");
            sb.AppendLine("</div>");
            sb.AppendLine("</body></html>");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            return path;
        }

    }
}