using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Autodesk.AutoCAD.DatabaseServices;
using HydroComplete.Civil3D.Reading;
using HydroComplete.Engine;

namespace HydroComplete.Civil3D.Writing
{
    /// <summary>
    /// Formula-transparent HTML report for Manning pipe capacity and steady HGL profiles.
    /// </summary>
    internal static class HtmlReportWriter
    {
        public static string Write(
            string drawingName,
            IReadOnlyList<ReadPipe> pipes,
            IReadOnlyDictionary<ObjectId, Manning.CapacityResult> capacities,
            HglReportData? hglData = null)
        {
            string path = ReportWriterCommon.BuildReportPath(drawingName, "html");

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\"/>");
            sb.AppendLine("<title>HydroComplete Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;margin:24px;color:#1a1a1a;}");
            sb.AppendLine("h1{font-size:1.4rem;} h2{font-size:1.15rem;margin-top:28px;}");
            sb.AppendLine("table{border-collapse:collapse;width:100%;margin:16px 0;}");
            sb.AppendLine("th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;font-size:0.9rem;}");
            sb.AppendLine("th{background:#f0f4f8;} tr.surcharged{background:#ffe6e6;}");
            sb.AppendLine(".steps{font-family:Consolas,monospace;font-size:0.85rem;}");
            sb.AppendLine(".disclaimer{margin-top:24px;padding:12px;background:#fff8e6;border:1px solid #e6c200;}");
            sb.AppendLine("</style></head><body>");
            sb.AppendLine("<h1>HydroComplete — Hydraulic Report</h1>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Drawing: <strong>{0}</strong><br/>Generated: {1}</p>",
                ReportWriterCommon.EscapeHtml(drawingName),
                ReportWriterCommon.EscapeHtml(DateTime.Now.ToString("f", CultureInfo.CurrentCulture))));

            AppendManningSection(sb, pipes, capacities);

            if (hglData != null && hglData.Networks.Count > 0)
                AppendHglSection(sb, hglData);

            sb.AppendLine("<div class=\"disclaimer\">");
            sb.AppendLine("<strong>Disclaimer:</strong> This report is generated by HydroComplete for preliminary ");
            sb.AppendLine("storm-sewer review. Verify all inputs (diameter, slope, roughness, design flow) ");
            sb.AppendLine("against the engineer's design basis. Not a substitute for licensed professional ");
            sb.AppendLine("judgment or jurisdiction-specific design standards.");
            sb.AppendLine("</div>");
            sb.AppendLine("</body></html>");

            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            return path;
        }

        private static void AppendManningSection(
            StringBuilder sb,
            IReadOnlyList<ReadPipe> pipes,
            IReadOnlyDictionary<ObjectId, Manning.CapacityResult> capacities)
        {
            sb.AppendLine("<h2>Manning Pipe Capacity</h2>");
            sb.AppendLine("<p>Method: Manning full-barrel capacity for circular pipes (US customary, n=0.013 default).</p>");

            sb.AppendLine("<table><thead><tr>");
            sb.AppendLine("<th>Network / Pipe</th><th>Dia (ft)</th><th>Slope</th><th>Q<sub>full</sub> (cfs)</th><th>V<sub>full</sub> (fps)</th>");
            sb.AppendLine("</tr></thead><tbody>");

            foreach (ReadPipe rp in pipes)
            {
                if (!capacities.TryGetValue(rp.PipeId, out Manning.CapacityResult? cap))
                    continue;

                sb.AppendLine("<tr>");
                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<td>{0}</td><td>{1:0.00}</td><td>{2:0.0000}</td><td>{3:0.00}</td><td>{4:0.00}</td>",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(rp.NetworkName + "/" + rp.PipeName, 48)),
                    rp.Segment.DiameterFt, rp.Segment.Slope,
                    cap.FullFlowCfs, cap.FullVelocityFps));
                sb.AppendLine("</tr>");
            }

            sb.AppendLine("</tbody></table>");

            sb.AppendLine("<h3>Manning calculation steps</h3>");
            foreach (ReadPipe rp in pipes)
            {
                if (!capacities.TryGetValue(rp.PipeId, out Manning.CapacityResult? cap))
                    continue;

                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<h4>{0}</h4><div class=\"steps\">",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(rp.NetworkName + "/" + rp.PipeName, 64))));
                foreach (CalcStep step in cap.Steps)
                    sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
                sb.AppendLine("</div>");
            }
        }

        private static void AppendHglSection(StringBuilder sb, HglReportData hglData)
        {
            string lossNote = hglData.IncludeMinorLosses ? " with HEC-22 junction/exit losses" : "";
            sb.AppendLine("<h2>Steady HGL Profile</h2>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "<p>Method: steady uniform-flow stepping downstream from headwater HGL " +
                "(S<sub>f</sub> = [n&middot;Q/(1.486&middot;A&middot;R<sup>2/3</sup>)]<sup>2</sup>, " +
                "h<sub>f</sub> = S<sub>f</sub>&middot;L, h<sub>m</sub> = K&middot;Vh){0}. " +
                "Design Q = <strong>{1:0.00} cfs</strong>.</p>",
                lossNote, hglData.DesignFlowCfs));

            foreach (HglNetworkReport net in hglData.Networks)
            {
                if (net.Rows.Count == 0) continue;

                sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "<h3>{0}</h3><p>Start HGL = {1:0.00} ft (max upstream invert + 1.0 ft freeboard).</p>",
                    ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(net.NetworkName, 64)), net.StartHglFt));

                sb.AppendLine("<table><thead><tr>");
                sb.AppendLine("<th>Pipe</th><th>h<sub>f</sub> (ft)</th><th>h<sub>m</sub> (ft)</th>");
                sb.AppendLine("<th>HGL<sub>US</sub> (ft)</th><th>HGL<sub>DS</sub> (ft)</th><th>SURCH</th>");
                sb.AppendLine("</tr></thead><tbody>");

                foreach (HglPipeReportRow row in net.Rows)
                {
                    string rowClass = row.IsSurcharged ? " class=\"surcharged\"" : "";
                    sb.AppendLine($"<tr{rowClass}>");
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<td>{0}</td><td>{1:0.00}</td><td>{2:0.00}</td><td>{3:0.00}</td><td>{4:0.00}</td><td>{5}</td>",
                        ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(row.PipeName, 48)),
                        row.Point.HfFt, row.Point.HmFt,
                        row.HglUsFt, row.HglDsFt,
                        row.IsSurcharged ? "*" : ""));
                    sb.AppendLine("</tr>");
                }

                sb.AppendLine("</tbody></table>");

                sb.AppendLine("<h4>HGL calculation steps</h4>");
                foreach (HglPipeReportRow row in net.Rows)
                {
                    sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                        "<h5>{0}</h5><div class=\"steps\">",
                        ReportWriterCommon.EscapeHtml(ReportWriterCommon.Trim(row.PipeName, 64))));
                    foreach (CalcStep step in row.Point.Steps)
                        sb.AppendLine(ReportWriterCommon.EscapeHtml(step.ToString()) + "<br/>");
                    sb.AppendLine("</div>");
                }
            }
        }

    }
}